// var promise = new Promise(function(resolve, reject) {
  
//   throw new Error('wtf')
//   resolve("ok");
//   //setTimeout(function() { throw new Error('test') }, 0)
// });
// promise.then(function(value) { console.log(value) })
//   .catch((err)=>{
//       console.log(err)
//   })
// process.on('unhandledRejection', function (err, p) {
//   console.error('catch exception:',err.stack)
// });
